export const Images = {
  Logos: {
    IElogo: "/assets/IElogo.svg",
    UspLogo: "/assets/UspLogo.svg",
    ThpLogo: "/assets/ThpLogo.svg",
    PipaLogo: "/assets/PipaLogo.svg",
    IcciLogo: "/assets/IcciLogo.svg",
    GifeLogo: "/assets/GifeLogo.svg",
    BejaLogoAnimadaBranca: "/assets/beja-logo-animada-branca.gif",
    BejaLogo: "/assets/BejaLogo.png",
    IDBRLogo: "/assets/IDBRLogo.svg",
    IDISLogo: "/assets/IDISLogo.svg",
    BlisLogo: "/assets/BlisLogo.svg",
    CriaLogo: "/assets/CriaLogo.svg",
    BejaLabsLogo: "/assets/BejaLogo.svg",
    PonteLogo: "/assets/PonteLogo.svg",
    YunusLogo: "/assets/YunusLogo.svg",
    CebrabLogo: "/assets/CebrabLogo.svg",
    IEBlisLogo: "/assets/IEBlisLogo.svg",
    SITAWILogo: "/assets/SITAWILogo.svg",
    AshokaLogo: "/assets/AshokaLogo.svg",
    ToribaLogo: "/assets/ToribaLogo.svg",
    DesJusLogo: "/assets/DesJusLogo.svg",
    IgapareLogo: "/assets/IgapareLogo.svg",
    CiraTHPLogo: "/assets/CiraTHPLogo.svg",
    SerenasLogo: "/assets/Serenas_logo.svg",
    PolitizeLogo: "/assets/PolitizeLogo.svg",
    DesenrolaLogo: "/assets/DesenrolaLogo.svg",
    MapBiomasLogo: "/assets/MapBiomasLogo.svg",
    ATAHUALPALogo: "/assets/ATAHUALPALogo.svg",
    AppCivicoLogo: "/assets/AppCivicoLogo.svg",
    ItauViverMais: "/assets/ItauViverMais.svg",
    MarAdentroLogo: "/assets/MarAdentroLogo.svg",
    CoalizacaoLogo: "/assets/CoalizacaoLogo.svg",
    FundoAgbaraLogo: "/assets/FundoAgbaraLogo.svg",
    DataPrivacyLogo: "/assets/DataPrivacyLogo.svg",
    LatimImpactoLogo: "/assets/LatimImpactoLogo.svg",
    MoreInCommonLogo: "/assets/MoreInCommonLogo.svg",
    CebrabDesjusLogo: "/assets/CebrabDesjusLogo.svg",
    InstitutoBejaLogo: "/assets/InstitutoBejaLogo.svg",
    PactoContraFomeLogo: "/assets/PactoContraFomeLogo.svg",
    FundacaoJoseLuizLogo: "/assets/FundacaoJoseLuizLogo.svg",
    LautELiberdadeAutoritarismo: "/assets/LautELiberdadeAutoritarismo.svg",
  },
  Ilustracoes: {
    Bush: "/assets/folhas.png",
    ProudHand: "/assets/Ilustracao-4.png",
    Clouds: "/assets/ilustracao-nuvens.png",
    FullClouds: "/assets/FullClouds.svg",
  },
  Secoes: {
    JusticaRacial: "/assets/JusticaRacial.svg",
    PelaDemocracia: "/assets/PelaDemocracia.svg",
    EquidadeGenero: "/assets/EquidadeGenero.svg",
    PelaDemocracia2: "/assets/PelaDemocracia2.svg",
    AliancaAdvocacy: "/assets/AliancaAdvocacy.svg",
    PazJusticaImage: "/assets/PazJusticaImage.png",
    MovimentoDoacao: "/assets/MovimentoDoacao.svg",
    FomeZeroAdvocacy: "/assets/FomeZeroAdvocacy.png",
    FilantropiaSubCard: "/assets/FilantropiaSubCard.svg",
  },
  Filantropando: {
    FilantropandoCCF: "/assets/FilantropandoCCF.svg",
    FilantropandoStar: "/assets/FilantropandoStar.svg",
    FilantropiaSlider1: "/assets/FilantropiaSlider1.svg",
    FilantropiaSlider2: "/assets/FilantropiaSlider2.svg",
    FilantropiaSlider3: "/assets/FilantropiaSlider3.svg",
    FilantropandoBanner: "/assets/FilantropandoBanner.svg",
    BubblesFilantropando: "/assets/BubblesFilantropando.png",
    FilantropandoBoasAcoes: "/assets/FilantropandoBoasAcoes.svg",
  },
  BejaLabs: {
    MapeamentoBrasil: "/assets/MapeamentoBrasil.svg",
    Globe: "/assets/Ilustracao-8.png",
  },
  CME: {
    CentroME: "/assets/LogoCME.svg",
    CMEWheel: "/assets/CMEWheel.svg",
    CMEGrafico: "/assets/CMEGrafico.svg",
    CmeMiniWheel1: "/assets/CmeMiniWheel1.svg",
    CmeMiniWheel2: "/assets/CmeMiniWheel2.svg",
    CmeMiniWheel3: "/assets/CmeMiniWheel3.svg",
  },
};
