import ForDemocracy from "./SubCards/ForDemocracy";
import FilantropandoCard from "./SubCards/Filantropando";
import EquidadeGeneroCard from "./SubCards/EquidadeGenero";
import JusticaRacialCard from "./SubCards/JusticaRacial";

export const Images = {
  Logos: {
    IElogo: "./assets/IElogo.svg",
    UspLogo: "./assets/UspLogo.svg",
    ThpLogo: "./assets/ThpLogo.svg",
    PipaLogo: "./assets/PipaLogo.svg",
    IcciLogo: "./assets/IcciLogo.svg",
    GifeLogo: "./assets/GifeLogo.svg",
    BejaLogoAnimadaBranca: "./assets/beja-logo-animada-branca.gif",
    BejaLogo: "./assets/BejaLogo.png",
    IDBRLogo: "./assets/IDBRLogo.svg",
    IDISLogo: "./assets/IDISLogo.svg",
    BlisLogo: "./assets/BlisLogo.svg",
    CriaLogo: "./assets/CriaLogo.svg",
    BejaLabsLogo: "./assets/BejaLogo.svg",
    PonteLogo: "./assets/PonteLogo.svg",
    YunusLogo: "./assets/YunusLogo.svg",
    CebrabLogo: "./assets/CebrabLogo.svg",
    IEBlisLogo: "./assets/IEBlisLogo.svg",
    SITAWILogo: "./assets/SITAWILogo.svg",
    AshokaLogo: "./assets/AshokaLogo.svg",
    ToribaLogo: "./assets/ToribaLogo.svg",
    DesJusLogo: "./assets/DesJusLogo.svg",
    IgapareLogo: "./assets/IgapareLogo.svg",
    CiraTHPLogo: "./assets/CiraTHPLogo.svg",
    SerenasLogo: "./assets/Serenas_logo.svg",
    PolitizeLogo: "./assets/PolitizeLogo.svg",
    DesenrolaLogo: "./assets/DesenrolaLogo.svg",
    MapBiomasLogo: "./assets/MapBiomasLogo.svg",
    ATAHUALPALogo: "./assets/ATAHUALPALogo.svg",
    AppCivicoLogo: "./assets/AppCivicoLogo.svg",
    ItauViverMais: "./assets/ItauViverMais.svg",
    MarAdentroLogo: "./assets/MarAdentroLogo.svg",
    CoalizacaoLogo: "./assets/CoalizacaoLogo.svg",
    FundoAgbaraLogo: "./assets/FundoAgbaraLogo.svg",
    DataPrivacyLogo: "./assets/DataPrivacyLogo.svg",
    LatimImpactoLogo: "./assets/LatimImpactoLogo.svg",
    MoreInCommonLogo: "./assets/MoreInCommonLogo.svg",
    CebrabDesjusLogo: "./assets/CebrabDesjusLogo.svg",
    InstitutoBejaLogo: "./assets/InstitutoBejaLogo.svg",
    PactoContraFomeLogo: "./assets/PactoContraFomeLogo.svg",
    FundacaoJoseLuizLogo: "./assets/FundacaoJoseLuizLogo.svg",
    LautELiberdadeAutoritarismo: "./assets/LautELiberdadeAutoritarismo.svg",
  },
  BejaHouse: {
    EspacoBeja1: "./assets/EspacoBeja.png",
    EspacoBeja2: "./assets/EspacoBeja2.png",
    EspacoBeja3: "./assets/EspacoBeja3.png",
    BejaHouseCard1: "./assets/BejaHouseCard1.jpg",
    BejaHouseCard2: "./assets/BejaHouseCard2.jpg",
    BejaHouseCard3: "./assets/BejaHouseCard3.jpg",
    BejaHouseCard4: "./assets/BejaHouseCard4.jpg",
    BejaHouseCard5: "./assets/BejaHouseCard5.jpg",
    BejaHouseCard6: "./assets/BejaHouseCard6.jpg",
    BejaHouseCard7: "./assets/BejaHouseCard7.jpg",
  },
  Ilustracoes: {
    Bush: "./assets/folhas.png",
    ProudHand: "./assets/Ilustracao-4.png",
    Clouds: "./assets/ilustracao-nuvens.png",
    FullClouds: "./assets/FullClouds.svg",
  },
  Secoes: {
    JusticaRacial: <JusticaRacialCard />,
    PelaDemocracia: "./assets/PelaDemocracia.svg",
    EquidadeGenero: <EquidadeGeneroCard />,
    PelaDemocracia2: <ForDemocracy />,
    AliancaAdvocacy: "./assets/AliancaAdvocacy.svg",
    PazJusticaImage: "./assets/PazJusticaImage.png",
    MovimentoDoacao: "./assets/MovimentoDoacao.svg",
    FomeZeroAdvocacy: "./assets/FomeZeroAdvocacy.png",
    FilantropiaSubCard: <FilantropandoCard />,
  },
  Filantropando: {
    FilantropandoCCF: "./assets/FilantropandoCCF.svg",
    FilantropandoStar: "./assets/FilantropandoStar.svg",
    FilantropiaSlider1: "./assets/FilantropiaSlider1.svg",
    FilantropiaSlider2: "./assets/FilantropiaSlider2.svg",
    FilantropiaSlider3: "./assets/FilantropiaSlider3.svg",
    FilantropandoCard1: "./assets/FilantropandoCard1.jpeg",
    FilantropandoCard2: "./assets/FilantropandoCard2.jpeg",
    FilantropandoCard3: "./assets/FilantropandoCard3.jpeg",
    FilantropandoCard4: "./assets/FilantropandoCard4.jpeg",
    FilantropandoCard5: "./assets/FilantropandoCard5.jpeg",
    FilantropandoCard6: "./assets/FilantropandoCard6.jpeg",
    FilantropandoCard7: "./assets/FilantropandoCard7.jpeg",
    FilantropandoBanner: "./assets/FilantropandoBanner.svg",
    BubblesFilantropando: "./assets/BubblesFilantropando.png",
    FilantropandoBoasAcoes: "./assets/FilantropandoBoasAcoes.svg",
  },
  BejaLabs: {
    MapeamentoBrasil: "./assets/MapeamentoBrasil.svg",
    Globe: "./assets/Ilustracao-8.png",
  },
  CME: {
    CentroME: "./assets/LogoCME.svg",
    CMEWheel: "./assets/CMEWheel.svg",
    CMEGrafico: "./assets/CMEGrafico.svg",
    EngCmeGrafico: "./assets/engCmeGraphic.png",
    CmeMiniWheel1: "./assets/CmeMiniWheel1.svg",
    CmeMiniWheel2: "./assets/CmeMiniWheel2.svg",
    CmeMiniWheel3: "./assets/CmeMiniWheel3.svg",
  },
};
